name: Production Pipeline (github-hosted)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build (nodejs ${{ matrix.node-version }})
    strategy:
      matrix:
        # even numbers are LTS releases
        # node-version: [18, 20, 22]
        node-version: [20, 22]

    steps:
      # equivalent of doing git clone
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        # ensures node.js is available
        uses: actions/setup-node@v4
        with:
          # reference different versions
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      # npm ci is equivalent to npm install but is specifically optimized for CI
      - run: npm ci
        working-directory: src
      - run: npm run build
        working-directory: src


  test:
    needs: build
    runs-on: ubuntu-latest
    name: test (nodejs ${{ matrix.node-version }})
    strategy:
      matrix:
        # even numbers are LTS releases
        node-version: [20, 22]
        # node-version: [18, 20, 22]

    steps:
      # equivalent of doing git clone
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        # ensures node.js is available
        uses: actions/setup-node@v4
        with:
          # reference different versions
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      # npm ci is equivalent to npm install but is specifically optimized for CI
      - run: npm ci
        working-directory: src
      - run: npm run build --prefix common
        working-directory: src
      - run: npm test
        working-directory: src

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_SKOGKURS }}'
      - name: Set up Google SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_SKOGKURS }}
          service_account_key: ${{ secrets.GCP_SA_KEY_SKOGKURS }}
          # allows gcloud to read credentials
          export_default_credentials: true
      - name: Installing dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
        working-directory: src
      - run: npm run build
        working-directory: src
      - name: Deploy to Google App Engine
        run: gcloud app deploy
        working-directory: src

